### ISSUE TITLE
你好，我在一个地方看到你的简历，不知道你是否找到工作了，有没兴趣聊聊？

### ISSUE THREAD

**Issue by zhonghuiping** [aicest/ded#1]
联系方式： qq－> 531569568

**Comment by aicest** [comment]
哈哈不了谢谢，刚入职3天。

**Comment by zhonghuiping** [comment]
哈哈，没事，在哪入职啦？
 
 
------------------ Original ------------------
From: "Kombu"; 
Date: 2016年1月11日(星期一) 下午4:20
To: "aicest/ded"; 
Cc: "zhonghuiping"; 
Subject: Re: [ded] 你好，我在一个地方看到你的简历，不知道你是否找到工作了，有没兴趣聊聊？ (#1)

 

哈哈不了谢谢，刚入职3天。
